on:
  push:
    branches:
      - main






jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'beforet'
        run: ls

      - uses: actions/checkout@v3  

      - name: 'after'
        run: ls
  
  
